name: Deploy to Databricks Workspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks
        run: |
          printf "%s\n%s\n" "${{ secrets.DATABRICKS_HOST }}" "${{ secrets.DATABRICKS_TOKEN }}" | databricks configure --token

      - name: Verify CLI
        run: databricks workspace ls /

      - name: Create Workspace Directory
        run: |
          databricks workspace mkdirs /Workspace/Users/sammaiahpenaka98@gmail.com/projects_handling/Deployments/cd_cal_math/

      - name: Upload Python file
        run: |
          databricks workspace import cal_math.py \
          /Workspace/Users/sammaiahpenaka98@gmail.com/projects_handling/Deployments/cd_cal_math/cal_math.py \
          --format SOURCE \
          --language PYTHON \
          --overwrite
